/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__number_thousands = 2,
  sym__number_hundreds = 3,
  sym__number_tens = 4,
  sym__number_ones = 5,
  anon_sym_PLUS = 6,
  anon_sym_DASH = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_PERCENT = 10,
  anon_sym_Sinon = 11,
  anon_sym_Munus = 12,
  anon_sym_EQ = 13,
  anon_sym_As = 14,
  anon_sym_Anagnosti = 15,
  anon_sym_Grafo = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  sym_source_file = 19,
  sym_number = 20,
  sym_addition = 21,
  sym_subtraction = 22,
  sym_multiplication = 23,
  sym_division = 24,
  sym_modulo = 25,
  sym__arithmetic_expression = 26,
  sym_branching = 27,
  sym_function_definition = 28,
  sym_function_call = 29,
  sym_variable_definition = 30,
  sym_assignment_statement = 31,
  sym_print_statement = 32,
  sym__parenthesized_expression = 33,
  sym__simple_expression = 34,
  sym__expression = 35,
  sym__statement = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_function_definition_repeat1 = 38,
  aux_sym_function_call_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__number_thousands] = "_number_thousands",
  [sym__number_hundreds] = "_number_hundreds",
  [sym__number_tens] = "_number_tens",
  [sym__number_ones] = "_number_ones",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_Sinon] = "Sinon",
  [anon_sym_Munus] = "Munus",
  [anon_sym_EQ] = "=",
  [anon_sym_As] = "As",
  [anon_sym_Anagnosti] = "Anagnosti",
  [anon_sym_Grafo] = "Grafo",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_number] = "number",
  [sym_addition] = "addition",
  [sym_subtraction] = "subtraction",
  [sym_multiplication] = "multiplication",
  [sym_division] = "division",
  [sym_modulo] = "modulo",
  [sym__arithmetic_expression] = "_arithmetic_expression",
  [sym_branching] = "branching",
  [sym_function_definition] = "function_definition",
  [sym_function_call] = "function_call",
  [sym_variable_definition] = "variable_definition",
  [sym_assignment_statement] = "assignment_statement",
  [sym_print_statement] = "print_statement",
  [sym__parenthesized_expression] = "_parenthesized_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym__expression] = "_expression",
  [sym__statement] = "_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_definition_repeat1] = "function_definition_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__number_thousands] = sym__number_thousands,
  [sym__number_hundreds] = sym__number_hundreds,
  [sym__number_tens] = sym__number_tens,
  [sym__number_ones] = sym__number_ones,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_Sinon] = anon_sym_Sinon,
  [anon_sym_Munus] = anon_sym_Munus,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_As] = anon_sym_As,
  [anon_sym_Anagnosti] = anon_sym_Anagnosti,
  [anon_sym_Grafo] = anon_sym_Grafo,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_number] = sym_number,
  [sym_addition] = sym_addition,
  [sym_subtraction] = sym_subtraction,
  [sym_multiplication] = sym_multiplication,
  [sym_division] = sym_division,
  [sym_modulo] = sym_modulo,
  [sym__arithmetic_expression] = sym__arithmetic_expression,
  [sym_branching] = sym_branching,
  [sym_function_definition] = sym_function_definition,
  [sym_function_call] = sym_function_call,
  [sym_variable_definition] = sym_variable_definition,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_print_statement] = sym_print_statement,
  [sym__parenthesized_expression] = sym__parenthesized_expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym__expression] = sym__expression,
  [sym__statement] = sym__statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_definition_repeat1] = aux_sym_function_definition_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__number_thousands] = {
    .visible = false,
    .named = true,
  },
  [sym__number_hundreds] = {
    .visible = false,
    .named = true,
  },
  [sym__number_tens] = {
    .visible = false,
    .named = true,
  },
  [sym__number_ones] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Sinon] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Munus] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_As] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Anagnosti] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Grafo] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_division] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym__arithmetic_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_branching] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesized_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_condition = 2,
  field_false_branch = 3,
  field_function = 4,
  field_left = 5,
  field_name = 6,
  field_right = 7,
  field_true_branch = 8,
  field_value = 9,
  field_variable = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_false_branch] = "false_branch",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
  [field_true_branch] = "true_branch",
  [field_value] = "value",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_left, 0},
    {field_right, 2},
  [3] =
    {field_function, 0},
  [4] =
    {field_value, 3},
    {field_variable, 1},
  [6] =
    {field_body, 4},
    {field_name, 1},
  [8] =
    {field_condition, 1},
    {field_false_branch, 2},
    {field_true_branch, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 13,
  [19] = 14,
  [20] = 15,
  [21] = 16,
  [22] = 17,
  [23] = 12,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 28,
  [35] = 26,
  [36] = 30,
  [37] = 32,
  [38] = 38,
  [39] = 31,
  [40] = 33,
  [41] = 29,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 56,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '%', 77,
        '(', 84,
        ')', 85,
        '*', 75,
        '+', 73,
        '-', 74,
        '/', 76,
        '=', 80,
        'A', 10,
        'C', 48,
        'D', 1,
        'G', 18,
        'I', 72,
        'L', 3,
        'M', 30,
        'N', 69,
        'S', 8,
        'V', 2,
        'X', 64,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == 'C') ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == 'I') ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == 'X') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(79);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '%', 77,
        '(', 84,
        ')', 85,
        '*', 75,
        '+', 73,
        '-', 74,
        '/', 76,
        'A', 19,
        'G', 18,
        'M', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__number_thousands);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(34);
      if (lookahead == 'D') ADVANCE(35);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'M') ADVANCE(31);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(34);
      if (lookahead == 'D') ADVANCE(35);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'M') ADVANCE(29);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(34);
      if (lookahead == 'D') ADVANCE(35);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(36);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(32);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(32);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      if (lookahead == 'D' ||
          lookahead == 'M') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'C') ADVANCE(33);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'L') ADVANCE(41);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'V') ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(38);
      if (lookahead == 'C' ||
          lookahead == 'L') ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(44);
      if (lookahead == 'V') ADVANCE(45);
      if (lookahead == 'X') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(28);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(42);
      if (lookahead == 'V' ||
          lookahead == 'X') ADVANCE(28);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__number_thousands);
      if (lookahead == 'I') ADVANCE(43);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__number_hundreds);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'C') ADVANCE(49);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'C') ADVANCE(49);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(54);
      if (lookahead == 'D' ||
          lookahead == 'M') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'C') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'V') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(52);
      if (lookahead == 'C' ||
          lookahead == 'L') ADVANCE(51);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(58);
      if (lookahead == 'V') ADVANCE(59);
      if (lookahead == 'X') ADVANCE(53);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(46);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(56);
      if (lookahead == 'V' ||
          lookahead == 'X') ADVANCE(46);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__number_hundreds);
      if (lookahead == 'I') ADVANCE(57);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__number_tens);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(67);
      if (lookahead == 'V') ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(67);
      if (lookahead == 'V') ADVANCE(68);
      if (lookahead == 'X') ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(67);
      if (lookahead == 'V') ADVANCE(68);
      if (lookahead == 'X') ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(67);
      if (lookahead == 'V') ADVANCE(68);
      if (lookahead == 'X') ADVANCE(62);
      if (lookahead == 'C' ||
          lookahead == 'L') ADVANCE(61);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(60);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(65);
      if (lookahead == 'V' ||
          lookahead == 'X') ADVANCE(60);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__number_tens);
      if (lookahead == 'I') ADVANCE(66);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__number_ones);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__number_ones);
      if (lookahead == 'I') ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__number_ones);
      if (lookahead == 'I') ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__number_ones);
      if (lookahead == 'I') ADVANCE(70);
      if (lookahead == 'V' ||
          lookahead == 'X') ADVANCE(69);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_Sinon);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_Munus);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_As);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_Anagnosti);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_Grafo);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 25},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 25},
  [35] = {.lex_state = 25},
  [36] = {.lex_state = 25},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 25},
  [41] = {.lex_state = 25},
  [42] = {.lex_state = 25},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 25},
  [45] = {.lex_state = 25},
  [46] = {.lex_state = 25},
  [47] = {.lex_state = 25},
  [48] = {.lex_state = 25},
  [49] = {.lex_state = 25},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__number_thousands] = ACTIONS(1),
    [sym__number_hundreds] = ACTIONS(1),
    [sym__number_tens] = ACTIONS(1),
    [sym__number_ones] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_Sinon] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_As] = ACTIONS(1),
    [anon_sym_Anagnosti] = ACTIONS(1),
    [anon_sym_Grafo] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym_function_definition] = STATE(43),
    [sym_variable_definition] = STATE(43),
    [sym_assignment_statement] = STATE(43),
    [sym_print_statement] = STATE(43),
    [sym__statement] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_Munus] = ACTIONS(7),
    [anon_sym_As] = ACTIONS(9),
    [anon_sym_Grafo] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_number] = STATE(3),
    [sym_addition] = STATE(3),
    [sym_subtraction] = STATE(3),
    [sym_multiplication] = STATE(3),
    [sym_division] = STATE(3),
    [sym_modulo] = STATE(3),
    [sym__arithmetic_expression] = STATE(3),
    [sym_branching] = STATE(3),
    [sym__parenthesized_expression] = STATE(3),
    [sym__simple_expression] = STATE(3),
    [sym_identifier] = ACTIONS(13),
    [sym__number_thousands] = ACTIONS(15),
    [sym__number_hundreds] = ACTIONS(15),
    [sym__number_tens] = ACTIONS(15),
    [sym__number_ones] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_Sinon] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_number] = STATE(34),
    [sym_addition] = STATE(34),
    [sym_subtraction] = STATE(34),
    [sym_multiplication] = STATE(34),
    [sym_division] = STATE(34),
    [sym_modulo] = STATE(34),
    [sym__arithmetic_expression] = STATE(34),
    [sym_branching] = STATE(34),
    [sym__parenthesized_expression] = STATE(34),
    [sym__simple_expression] = STATE(34),
    [sym_identifier] = ACTIONS(31),
    [sym__number_thousands] = ACTIONS(33),
    [sym__number_hundreds] = ACTIONS(33),
    [sym__number_tens] = ACTIONS(33),
    [sym__number_ones] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_Sinon] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym_number] = STATE(28),
    [sym_addition] = STATE(28),
    [sym_subtraction] = STATE(28),
    [sym_multiplication] = STATE(28),
    [sym_division] = STATE(28),
    [sym_modulo] = STATE(28),
    [sym__arithmetic_expression] = STATE(28),
    [sym_branching] = STATE(28),
    [sym__parenthesized_expression] = STATE(28),
    [sym__simple_expression] = STATE(28),
    [sym_identifier] = ACTIONS(39),
    [sym__number_thousands] = ACTIONS(15),
    [sym__number_hundreds] = ACTIONS(15),
    [sym__number_tens] = ACTIONS(15),
    [sym__number_ones] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_Sinon] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
  },
  [STATE(5)] = {
    [sym_number] = STATE(4),
    [sym_addition] = STATE(4),
    [sym_subtraction] = STATE(4),
    [sym_multiplication] = STATE(4),
    [sym_division] = STATE(4),
    [sym_modulo] = STATE(4),
    [sym__arithmetic_expression] = STATE(4),
    [sym_branching] = STATE(4),
    [sym__parenthesized_expression] = STATE(4),
    [sym__simple_expression] = STATE(4),
    [sym_identifier] = ACTIONS(41),
    [sym__number_thousands] = ACTIONS(15),
    [sym__number_hundreds] = ACTIONS(15),
    [sym__number_tens] = ACTIONS(15),
    [sym__number_ones] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_Sinon] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_Anagnosti,
    STATE(49), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [35] = 6,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(47), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [67] = 6,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(48), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [99] = 6,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(46), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [131] = 6,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(56), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [163] = 6,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(57), 2,
      sym_function_call,
      sym__expression,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(38), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [195] = 5,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(41), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [223] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(5), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [251] = 5,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(37), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [279] = 5,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      sym_identifier,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(39), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [307] = 5,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(36), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [335] = 5,
    ACTIONS(35), 1,
      anon_sym_Sinon,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(33), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(40), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [363] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(2), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [391] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(32), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [419] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(31), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [447] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(30), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [475] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(33), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [503] = 5,
    ACTIONS(27), 1,
      anon_sym_Sinon,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(15), 4,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
    STATE(29), 10,
      sym_number,
      sym_addition,
      sym_subtraction,
      sym_multiplication,
      sym_division,
      sym_modulo,
      sym__arithmetic_expression,
      sym_branching,
      sym__parenthesized_expression,
      sym__simple_expression,
  [531] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(45), 2,
      sym__parenthesized_expression,
      aux_sym_function_call_repeat1,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [552] = 1,
    ACTIONS(73), 12,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [567] = 1,
    ACTIONS(75), 12,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [582] = 1,
    ACTIONS(73), 12,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [597] = 6,
    ACTIONS(17), 1,
      anon_sym_PLUS,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      anon_sym_PERCENT,
    ACTIONS(77), 7,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [622] = 1,
    ACTIONS(79), 12,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [637] = 1,
    ACTIONS(81), 12,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [652] = 4,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      anon_sym_PERCENT,
    ACTIONS(83), 9,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [673] = 4,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      anon_sym_PERCENT,
    ACTIONS(85), 9,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [694] = 1,
    ACTIONS(87), 12,
      sym_identifier,
      sym__number_thousands,
      sym__number_hundreds,
      sym__number_tens,
      sym__number_ones,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Sinon,
      anon_sym_LPAREN,
  [709] = 6,
    ACTIONS(89), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_PERCENT,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [733] = 1,
    ACTIONS(75), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [747] = 1,
    ACTIONS(81), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [761] = 4,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_PERCENT,
    ACTIONS(85), 8,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [781] = 6,
    ACTIONS(89), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_PERCENT,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [805] = 4,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_PERCENT,
    ACTIONS(83), 8,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [825] = 1,
    ACTIONS(87), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [839] = 1,
    ACTIONS(79), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [853] = 6,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      sym_identifier,
    ACTIONS(106), 1,
      anon_sym_Munus,
    ACTIONS(109), 1,
      anon_sym_As,
    ACTIONS(112), 1,
      anon_sym_Grafo,
    STATE(42), 6,
      sym_function_definition,
      sym_variable_definition,
      sym_assignment_statement,
      sym_print_statement,
      sym__statement,
      aux_sym_source_file_repeat1,
  [877] = 6,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_Munus,
    ACTIONS(9), 1,
      anon_sym_As,
    ACTIONS(11), 1,
      anon_sym_Grafo,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    STATE(42), 6,
      sym_function_definition,
      sym_variable_definition,
      sym_assignment_statement,
      sym_print_statement,
      sym__statement,
      aux_sym_source_file_repeat1,
  [901] = 3,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    STATE(44), 2,
      sym__parenthesized_expression,
      aux_sym_function_call_repeat1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [917] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(44), 2,
      sym__parenthesized_expression,
      aux_sym_function_call_repeat1,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
      anon_sym_RPAREN,
  [933] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
  [941] = 1,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
  [949] = 1,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
  [957] = 1,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_Munus,
      anon_sym_As,
      anon_sym_Grafo,
  [965] = 3,
    ACTIONS(132), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_EQ,
    STATE(51), 1,
      aux_sym_function_definition_repeat1,
  [975] = 3,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(139), 1,
      anon_sym_EQ,
    STATE(51), 1,
      aux_sym_function_definition_repeat1,
  [985] = 2,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(50), 1,
      aux_sym_function_definition_repeat1,
  [992] = 1,
    ACTIONS(143), 1,
      sym_identifier,
  [996] = 1,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
  [1000] = 1,
    ACTIONS(147), 1,
      sym_identifier,
  [1004] = 1,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [1008] = 1,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
  [1012] = 1,
    ACTIONS(153), 1,
      anon_sym_EQ,
  [1016] = 1,
    ACTIONS(155), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 35,
  [SMALL_STATE(8)] = 67,
  [SMALL_STATE(9)] = 99,
  [SMALL_STATE(10)] = 131,
  [SMALL_STATE(11)] = 163,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 251,
  [SMALL_STATE(15)] = 279,
  [SMALL_STATE(16)] = 307,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 391,
  [SMALL_STATE(20)] = 419,
  [SMALL_STATE(21)] = 447,
  [SMALL_STATE(22)] = 475,
  [SMALL_STATE(23)] = 503,
  [SMALL_STATE(24)] = 531,
  [SMALL_STATE(25)] = 552,
  [SMALL_STATE(26)] = 567,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 597,
  [SMALL_STATE(29)] = 622,
  [SMALL_STATE(30)] = 637,
  [SMALL_STATE(31)] = 652,
  [SMALL_STATE(32)] = 673,
  [SMALL_STATE(33)] = 694,
  [SMALL_STATE(34)] = 709,
  [SMALL_STATE(35)] = 733,
  [SMALL_STATE(36)] = 747,
  [SMALL_STATE(37)] = 761,
  [SMALL_STATE(38)] = 781,
  [SMALL_STATE(39)] = 805,
  [SMALL_STATE(40)] = 825,
  [SMALL_STATE(41)] = 839,
  [SMALL_STATE(42)] = 853,
  [SMALL_STATE(43)] = 877,
  [SMALL_STATE(44)] = 901,
  [SMALL_STATE(45)] = 917,
  [SMALL_STATE(46)] = 933,
  [SMALL_STATE(47)] = 941,
  [SMALL_STATE(48)] = 949,
  [SMALL_STATE(49)] = 957,
  [SMALL_STATE(50)] = 965,
  [SMALL_STATE(51)] = 975,
  [SMALL_STATE(52)] = 985,
  [SMALL_STATE(53)] = 992,
  [SMALL_STATE(54)] = 996,
  [SMALL_STATE(55)] = 1000,
  [SMALL_STATE(56)] = 1004,
  [SMALL_STATE(57)] = 1008,
  [SMALL_STATE(58)] = 1012,
  [SMALL_STATE(59)] = 1016,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesized_expression, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branching, 4, 0, 6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modulo, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtraction, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 2, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 4, 0, 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_definition_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [145] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_romulus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "romulus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
